import { MigrationInterface, QueryRunner } from "typeorm";

export class InicialEsquemaCompleto1788466300932 implements MigrationInterface {
    name = 'InicialEsquemaCompleto1788466300932'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "historial_expediente" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expedienteId" character varying NOT NULL, "snapshotAnterior" jsonb NOT NULL, "snapshotNuevo" jsonb NOT NULL, "camposModificados" text array NOT NULL, "usuarioId" character varying NOT NULL, "motivo" text, "ipDispositivo" character varying, "esRestauracion" boolean NOT NULL DEFAULT false, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_044d682ba53d040ddc31c093814" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_02cb796885023d814313744065" ON "historial_expediente"  ("expedienteId", "creadoEn") `);
        await queryRunner.query(`CREATE TYPE "public"."agenda_eventos_tipo_enum" AS ENUM('audiencia', 'cita', 'reunion', 'deposito', 'seguimiento', 'vencimiento', 'llamada', 'tarea_interna', 'plazo_judicial')`);
        await queryRunner.query(`CREATE TYPE "public"."agenda_eventos_prioridad_enum" AS ENUM('baja', 'media', 'alta', 'urgente')`);
        await queryRunner.query(`CREATE TYPE "public"."agenda_eventos_estado_enum" AS ENUM('pendiente', 'confirmado', 'completado', 'cancelado', 'reprogramado')`);
        await queryRunner.query(`CREATE TABLE "agenda_eventos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo" "public"."agenda_eventos_tipo_enum" NOT NULL, "titulo" character varying NOT NULL, "expedienteId" character varying, "clienteId" character varying, "fechaHoraInicio" TIMESTAMP NOT NULL, "fechaHoraFin" TIMESTAMP, "responsableId" character varying NOT NULL, "colaboradores" text array NOT NULL DEFAULT '{}', "prioridad" "public"."agenda_eventos_prioridad_enum" NOT NULL DEFAULT 'media', "estado" "public"."agenda_eventos_estado_enum" NOT NULL DEFAULT 'pendiente', "recordatorioMinutosAntes" integer, "observaciones" text, "creadoPorId" character varying NOT NULL, "googleEventId" character varying, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef4381e532e0c8d9cf3098532e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_agenda_evento_google_unico" ON "agenda_eventos"  ("googleEventId") WHERE "googleEventId" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_8f90e6b17fcce08c8cb49c7993" ON "agenda_eventos"  ("responsableId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4afa8ec0a4a8780ded7f6b170e" ON "agenda_eventos"  ("fechaHoraInicio") `);
        await queryRunner.query(`CREATE TYPE "public"."alertas_reglas_config_tiporegla_enum" AS ENUM('expediente_sin_movimiento', 'plazo_proximo', 'plazo_vencido', 'documento_vencido', 'requisito_pendiente_vencido', 'evento_proximo', 'evento_vencido', 'factura_vencida')`);
        await queryRunner.query(`CREATE TYPE "public"."alertas_reglas_config_severidaddefault_enum" AS ENUM('informativa', 'atencion', 'urgente', 'critica')`);
        await queryRunner.query(`CREATE TABLE "alertas_reglas_config" ("tipoRegla" "public"."alertas_reglas_config_tiporegla_enum" NOT NULL, "activa" boolean NOT NULL DEFAULT true, "umbralDias" integer, "severidadDefault" "public"."alertas_reglas_config_severidaddefault_enum" NOT NULL, CONSTRAINT "PK_65af05e7daab1841d874d8b6e02" PRIMARY KEY ("tipoRegla"))`);
        await queryRunner.query(`CREATE TYPE "public"."alertas_tiporegla_enum" AS ENUM('expediente_sin_movimiento', 'plazo_proximo', 'plazo_vencido', 'documento_vencido', 'requisito_pendiente_vencido', 'evento_proximo', 'evento_vencido', 'factura_vencida')`);
        await queryRunner.query(`CREATE TYPE "public"."alertas_severidad_enum" AS ENUM('informativa', 'atencion', 'urgente', 'critica')`);
        await queryRunner.query(`CREATE TABLE "alertas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipoRegla" "public"."alertas_tiporegla_enum" NOT NULL, "severidad" "public"."alertas_severidad_enum" NOT NULL, "expedienteId" character varying, "clienteId" character varying, "documentoId" character varying, "agendaEventoId" character varying, "facturaId" character varying, "mensaje" text NOT NULL, "usuarioDestinatarioId" character varying, "vista" boolean NOT NULL DEFAULT false, "vistaEn" TIMESTAMP, "resuelta" boolean NOT NULL DEFAULT false, "resueltaEn" TIMESTAMP, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b474c4021f8d6e4e13383ef1106" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc75524402b33793400a38fa9e" ON "alertas"  ("resuelta") `);
        await queryRunner.query(`CREATE INDEX "IDX_2309f35d045780adc9544c1d6b" ON "alertas"  ("expedienteId") `);
        await queryRunner.query(`CREATE TYPE "public"."clientes_tipo_enum" AS ENUM('fisico', 'juridico')`);
        await queryRunner.query(`CREATE TYPE "public"."clientes_estadocivil_enum" AS ENUM('soltero', 'casado', 'divorciado', 'viudo', 'union_libre')`);
        await queryRunner.query(`CREATE TYPE "public"."clientes_estado_enum" AS ENUM('activo', 'prospecto', 'inactivo')`);
        await queryRunner.query(`CREATE TABLE "clientes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo" "public"."clientes_tipo_enum" NOT NULL, "codigoCliente" character varying NOT NULL, "nombres" character varying, "apellidos" character varying, "fechaNacimiento" date, "estadoCivil" "public"."clientes_estadocivil_enum", "ocupacion" character varying, "razonSocial" character varying, "nombreComercial" character varying, "registroMercantil" character varying, "domicilioSocial" character varying, "representanteLegal" character varying, "cedulaOPasaporteRepresentante" character varying, "actividadComercial" character varying, "cedula" character varying, "pasaporte" character varying, "rnc" character varying, "nacionalidad" character varying NOT NULL, "direccion" character varying NOT NULL, "telefonos" text array NOT NULL DEFAULT '{}', "correo" character varying, "personaContacto" character varying, "observaciones" text, "estado" "public"."clientes_estado_enum" NOT NULL DEFAULT 'prospecto', "creadoPorId" character varying, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f00637641796cb22d899c9a5a88" UNIQUE ("codigoCliente"), CONSTRAINT "PK_d76bf3571d906e4e86470482c08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_cliente_cedula_unica" ON "clientes"  ("cedula") WHERE "cedula" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_cliente_pasaporte_unico" ON "clientes"  ("pasaporte") WHERE "pasaporte" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_cliente_rnc_unico" ON "clientes"  ("rnc") WHERE "rnc" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_cliente_correo_unico" ON "clientes"  ("correo") WHERE "correo" IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."documento_permisos_rol_enum" AS ENUM('superadministrador', 'abogado_administrador', 'abogado_asociado', 'asistente_paralegal', 'facturacion_contabilidad', 'recepcion')`);
        await queryRunner.query(`CREATE TABLE "documento_permisos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "documentoId" character varying NOT NULL, "rol" "public"."documento_permisos_rol_enum" NOT NULL, "puedeVer" boolean NOT NULL DEFAULT true, "puedeDescargar" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6ddd59164c90acb6211120a15f3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."documentos_categoria_enum" AS ENUM('identificacion', 'poderes', 'contratos', 'instancias', 'actos_alguacil', 'pruebas', 'certificaciones', 'sentencias', 'resoluciones', 'facturas', 'recibos', 'correspondencias', 'informes', 'formularios', 'otros')`);
        await queryRunner.query(`CREATE TYPE "public"."documentos_estadocalidad_enum" AS ENUM('legible', 'ilegible', 'requiere_traduccion', 'requiere_apostilla', 'requiere_legalizacion')`);
        await queryRunner.query(`CREATE TABLE "documentos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expedienteId" character varying, "clienteId" character varying, "carpeta" character varying NOT NULL DEFAULT 'General', "categoria" "public"."documentos_categoria_enum" NOT NULL, "nombreArchivo" character varying NOT NULL, "descripcion" text, "rutaAlmacenamiento" character varying NOT NULL, "tipoMime" character varying NOT NULL, "tamanoBytes" integer NOT NULL, "version" integer NOT NULL DEFAULT '1', "documentoPadreId" uuid, "confidencial" boolean NOT NULL DEFAULT false, "clienteVisible" boolean NOT NULL DEFAULT false, "fechaVencimiento" date, "estadoCalidad" "public"."documentos_estadocalidad_enum" NOT NULL DEFAULT 'legible', "subidoPorId" character varying NOT NULL, "subidoEn" TIMESTAMP NOT NULL DEFAULT now(), "eliminadoEn" TIMESTAMP, "eliminadoPorId" character varying, CONSTRAINT "PK_30b7ee230a352e7582842d1dc02" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3363230c2b17fd4a0a564baa78" ON "documentos"  ("clienteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfe7ea1972f8454c32b6da960f" ON "documentos"  ("expedienteId") `);
        await queryRunner.query(`CREATE TYPE "public"."expedientes_materia_enum" AS ENUM('civil', 'comercial', 'penal', 'laboral', 'familia', 'inmobiliario', 'migratorio', 'administrativo', 'constitucional', 'registro_civil_jce', 'notarial', 'corporativo', 'propiedad_intelectual', 'cobros', 'proteccion_consumidor', 'seguridad_social', 'otra')`);
        await queryRunner.query(`CREATE TYPE "public"."expedientes_prioridad_enum" AS ENUM('baja', 'media', 'alta', 'urgente')`);
        await queryRunner.query(`CREATE TYPE "public"."expedientes_riesgo_enum" AS ENUM('bajo', 'medio', 'alto')`);
        await queryRunner.query(`CREATE TYPE "public"."expedientes_estado_enum" AS ENUM('prospecto', 'pendiente_contratacion', 'abierto', 'en_preparacion', 'pendiente_documentos', 'listo_para_depositar', 'depositado', 'en_revision_institucional', 'pendiente_respuesta', 'audiencia_fijada', 'en_audiencia', 'pendiente_decision', 'sentencia_emitida', 'en_recurso', 'en_ejecucion', 'suspendido', 'cerrado_favorablemente', 'cerrado_desfavorablemente', 'archivado')`);
        await queryRunner.query(`CREATE TABLE "expedientes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying NOT NULL, "numeroJudicial" character varying, "clienteId" uuid NOT NULL, "contraparte" character varying, "abogadoResponsableId" uuid, "materia" "public"."expedientes_materia_enum" NOT NULL, "tipoServicio" character varying, "descripcion" text, "objetivo" text, "tribunalInstitucion" character varying, "fechaApertura" date, "fechaDeposito" date, "proximaActuacion" date, "fechaLimite" date, "prioridad" "public"."expedientes_prioridad_enum" NOT NULL DEFAULT 'media', "riesgo" "public"."expedientes_riesgo_enum" NOT NULL DEFAULT 'bajo', "honorariosAcordados" numeric(12,2), "balancePendiente" numeric(12,2) NOT NULL DEFAULT '0', "estado" "public"."expedientes_estado_enum" NOT NULL DEFAULT 'prospecto', "etiquetas" text array NOT NULL DEFAULT '{}', "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f68ac4b08f02ba72e79e85934d5" UNIQUE ("codigo"), CONSTRAINT "PK_a5ea29a2665df2319ecbb8f4408" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cotizaciones_estado_enum" AS ENUM('borrador', 'enviada', 'aceptada', 'rechazada', 'convertida')`);
        await queryRunner.query(`CREATE TABLE "cotizaciones" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "numero" character varying NOT NULL, "clienteId" uuid NOT NULL, "expedienteId" uuid, "concepto" character varying NOT NULL, "items" jsonb NOT NULL, "aplicaItbis" boolean NOT NULL DEFAULT true, "subtotal" numeric(12,2) NOT NULL, "descuento" numeric(12,2) NOT NULL DEFAULT '0', "itbis" numeric(12,2) NOT NULL, "total" numeric(12,2) NOT NULL, "estado" "public"."cotizaciones_estado_enum" NOT NULL DEFAULT 'borrador', "validaHasta" date, "notas" text, "condicionesPago" character varying, "numeroOrdenCompra" character varying, "vendedor" character varying, "direccionFacturacion" text, "direccionEnvio" text, "costoEnvio" numeric(12,2) NOT NULL DEFAULT '0', "creadoPorId" character varying, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3bdc969a707929907861b09b6a2" UNIQUE ("numero"), CONSTRAINT "PK_4fcc685d6bca9b3a997ba9cd3bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."facturas_estado_enum" AS ENUM('pendiente', 'pagada_parcial', 'pagada', 'anulada')`);
        await queryRunner.query(`CREATE TABLE "facturas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "numero" character varying NOT NULL, "ncf" character varying, "clienteId" uuid NOT NULL, "expedienteId" uuid, "cotizacionId" character varying, "concepto" character varying NOT NULL, "items" jsonb NOT NULL, "aplicaItbis" boolean NOT NULL DEFAULT true, "subtotal" numeric(12,2) NOT NULL, "descuento" numeric(12,2) NOT NULL DEFAULT '0', "itbis" numeric(12,2) NOT NULL, "total" numeric(12,2) NOT NULL, "montoPagado" numeric(12,2) NOT NULL DEFAULT '0', "estado" "public"."facturas_estado_enum" NOT NULL DEFAULT 'pendiente', "fechaEmision" date NOT NULL, "fechaVencimiento" date, "notas" text, "condicionesPago" character varying, "numeroOrdenCompra" character varying, "vendedor" character varying, "direccionFacturacion" text, "direccionEnvio" text, "costoEnvio" numeric(12,2) NOT NULL DEFAULT '0', "creadoPorId" character varying, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e96e0896b0f2a4319d61fcf9ff7" UNIQUE ("numero"), CONSTRAINT "PK_f302947c1e4773639b20707a8bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pagos_metodo_enum" AS ENUM('efectivo', 'transferencia', 'cheque', 'tarjeta', 'otro')`);
        await queryRunner.query(`CREATE TABLE "pagos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "facturaId" uuid NOT NULL, "monto" numeric(12,2) NOT NULL, "metodo" "public"."pagos_metodo_enum" NOT NULL, "referencia" character varying, "fecha" date NOT NULL, "notas" text, "registradoPorId" character varying, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_37321ca70a2ed50885dc205beb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."expediente_requisitos_estado_enum" AS ENUM('pendiente', 'en_proceso', 'completo', 'no_aplica')`);
        await queryRunner.query(`CREATE TABLE "expediente_requisitos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expedienteId" character varying NOT NULL, "requisitoPlantillaId" character varying, "nombreRequisito" character varying NOT NULL, "descripcion" text, "obligatorio" boolean NOT NULL DEFAULT true, "orden" integer NOT NULL DEFAULT '0', "estado" "public"."expediente_requisitos_estado_enum" NOT NULL DEFAULT 'pendiente', "responsableId" character varying, "fechaPrometida" date, "fechaCompletado" date, "documentoId" character varying, "observaciones" text, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b01a2933e860e8a20beb9d64bc7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2a4e5863f0f7a28f9de03e62d1" ON "expediente_requisitos"  ("expedienteId") `);
        await queryRunner.query(`CREATE TYPE "public"."requisitos_plantilla_materia_enum" AS ENUM('civil', 'comercial', 'penal', 'laboral', 'familia', 'inmobiliario', 'migratorio', 'administrativo', 'constitucional', 'registro_civil_jce', 'notarial', 'corporativo', 'propiedad_intelectual', 'cobros', 'proteccion_consumidor', 'seguridad_social', 'otra')`);
        await queryRunner.query(`CREATE TABLE "requisitos_plantilla" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "materia" "public"."requisitos_plantilla_materia_enum" NOT NULL, "tipoServicio" character varying, "nombreRequisito" character varying NOT NULL, "descripcion" text, "obligatorio" boolean NOT NULL DEFAULT true, "orden" integer NOT NULL DEFAULT '0', "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_079d798584c44b066b91878b0c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."solicitudes_documento_estado_enum" AS ENUM('pendiente_cliente', 'pendiente_aprobacion', 'aprobado', 'rechazado')`);
        await queryRunner.query(`CREATE TABLE "solicitudes_documento" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plantillaClave" character varying NOT NULL, "expedienteId" character varying, "clienteId" character varying, "estado" "public"."solicitudes_documento_estado_enum" NOT NULL DEFAULT 'pendiente_cliente', "datos" jsonb NOT NULL DEFAULT '{}', "tokenAcceso" character varying NOT NULL, "creadoPorId" character varying, "precio" numeric(10,2) NOT NULL DEFAULT '0', "pagoConfirmado" boolean NOT NULL DEFAULT false, "pagoConfirmadoEn" TIMESTAMP, "pagoConfirmadoPorId" character varying, "referenciaPago" character varying, "notasInternas" text, "motivoRechazo" text, "documentoGeneradoId" character varying, "revisadoPorId" character varying, "completadoEn" TIMESTAMP, "revisadoEn" TIMESTAMP, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8e9c84cfdca37fd26d7c115fec9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_solicitud_documento_token_unico" ON "solicitudes_documento"  ("tokenAcceso") `);
        await queryRunner.query(`CREATE INDEX "IDX_b7baad5b8e248ea6ea63274110" ON "solicitudes_documento"  ("clienteId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4adfa7f9d31b34fe80485a19ab" ON "solicitudes_documento"  ("expedienteId") `);
        await queryRunner.query(`CREATE TYPE "public"."usuarios_rol_enum" AS ENUM('superadministrador', 'abogado_administrador', 'abogado_asociado', 'asistente_paralegal', 'facturacion_contabilidad', 'recepcion')`);
        await queryRunner.query(`CREATE TYPE "public"."usuarios_estado_enum" AS ENUM('activo', 'suspendido', 'invitado')`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombreCompleto" character varying NOT NULL, "correo" character varying NOT NULL, "passwordHash" character varying NOT NULL, "rol" "public"."usuarios_rol_enum" NOT NULL, "estado" "public"."usuarios_estado_enum" NOT NULL DEFAULT 'activo', "dosFactorActivo" boolean NOT NULL DEFAULT false, "dosFactorSecreto" character varying, "ultimoAcceso" TIMESTAMP, "creadoEn" TIMESTAMP NOT NULL DEFAULT now(), "actualizadoEn" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_63665765c1a778a770c9bd585d" ON "usuarios"  ("correo") `);
        await queryRunner.query(`ALTER TABLE "expedientes" ADD CONSTRAINT "FK_cb26e708b1901ff3b64d48ce738" FOREIGN KEY ("clienteId") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotizaciones" ADD CONSTRAINT "FK_7a7f77d7f881bbc1de890dfe4f1" FOREIGN KEY ("clienteId") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cotizaciones" ADD CONSTRAINT "FK_b5510b882cdbb795a8a2ec99366" FOREIGN KEY ("expedienteId") REFERENCES "expedientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facturas" ADD CONSTRAINT "FK_be6dba2298d9414913463f492bb" FOREIGN KEY ("clienteId") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facturas" ADD CONSTRAINT "FK_4ede75104badd0c792ce0f0d575" FOREIGN KEY ("expedienteId") REFERENCES "expedientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pagos" ADD CONSTRAINT "FK_b36661779d46a7d34a88fd2ab1e" FOREIGN KEY ("facturaId") REFERENCES "facturas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "pagos" DROP CONSTRAINT "FK_b36661779d46a7d34a88fd2ab1e"`);
        await queryRunner.query(`ALTER TABLE "facturas" DROP CONSTRAINT "FK_4ede75104badd0c792ce0f0d575"`);
        await queryRunner.query(`ALTER TABLE "facturas" DROP CONSTRAINT "FK_be6dba2298d9414913463f492bb"`);
        await queryRunner.query(`ALTER TABLE "cotizaciones" DROP CONSTRAINT "FK_b5510b882cdbb795a8a2ec99366"`);
        await queryRunner.query(`ALTER TABLE "cotizaciones" DROP CONSTRAINT "FK_7a7f77d7f881bbc1de890dfe4f1"`);
        await queryRunner.query(`ALTER TABLE "expedientes" DROP CONSTRAINT "FK_cb26e708b1901ff3b64d48ce738"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63665765c1a778a770c9bd585d"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TYPE "public"."usuarios_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."usuarios_rol_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4adfa7f9d31b34fe80485a19ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b7baad5b8e248ea6ea63274110"`);
        await queryRunner.query(`DROP INDEX "public"."idx_solicitud_documento_token_unico"`);
        await queryRunner.query(`DROP TABLE "solicitudes_documento"`);
        await queryRunner.query(`DROP TYPE "public"."solicitudes_documento_estado_enum"`);
        await queryRunner.query(`DROP TABLE "requisitos_plantilla"`);
        await queryRunner.query(`DROP TYPE "public"."requisitos_plantilla_materia_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a4e5863f0f7a28f9de03e62d1"`);
        await queryRunner.query(`DROP TABLE "expediente_requisitos"`);
        await queryRunner.query(`DROP TYPE "public"."expediente_requisitos_estado_enum"`);
        await queryRunner.query(`DROP TABLE "pagos"`);
        await queryRunner.query(`DROP TYPE "public"."pagos_metodo_enum"`);
        await queryRunner.query(`DROP TABLE "facturas"`);
        await queryRunner.query(`DROP TYPE "public"."facturas_estado_enum"`);
        await queryRunner.query(`DROP TABLE "cotizaciones"`);
        await queryRunner.query(`DROP TYPE "public"."cotizaciones_estado_enum"`);
        await queryRunner.query(`DROP TABLE "expedientes"`);
        await queryRunner.query(`DROP TYPE "public"."expedientes_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expedientes_riesgo_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expedientes_prioridad_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expedientes_materia_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfe7ea1972f8454c32b6da960f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3363230c2b17fd4a0a564baa78"`);
        await queryRunner.query(`DROP TABLE "documentos"`);
        await queryRunner.query(`DROP TYPE "public"."documentos_estadocalidad_enum"`);
        await queryRunner.query(`DROP TYPE "public"."documentos_categoria_enum"`);
        await queryRunner.query(`DROP TABLE "documento_permisos"`);
        await queryRunner.query(`DROP TYPE "public"."documento_permisos_rol_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cliente_correo_unico"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cliente_rnc_unico"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cliente_pasaporte_unico"`);
        await queryRunner.query(`DROP INDEX "public"."idx_cliente_cedula_unica"`);
        await queryRunner.query(`DROP TABLE "clientes"`);
        await queryRunner.query(`DROP TYPE "public"."clientes_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."clientes_estadocivil_enum"`);
        await queryRunner.query(`DROP TYPE "public"."clientes_tipo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2309f35d045780adc9544c1d6b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc75524402b33793400a38fa9e"`);
        await queryRunner.query(`DROP TABLE "alertas"`);
        await queryRunner.query(`DROP TYPE "public"."alertas_severidad_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alertas_tiporegla_enum"`);
        await queryRunner.query(`DROP TABLE "alertas_reglas_config"`);
        await queryRunner.query(`DROP TYPE "public"."alertas_reglas_config_severidaddefault_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alertas_reglas_config_tiporegla_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4afa8ec0a4a8780ded7f6b170e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f90e6b17fcce08c8cb49c7993"`);
        await queryRunner.query(`DROP INDEX "public"."idx_agenda_evento_google_unico"`);
        await queryRunner.query(`DROP TABLE "agenda_eventos"`);
        await queryRunner.query(`DROP TYPE "public"."agenda_eventos_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."agenda_eventos_prioridad_enum"`);
        await queryRunner.query(`DROP TYPE "public"."agenda_eventos_tipo_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02cb796885023d814313744065"`);
        await queryRunner.query(`DROP TABLE "historial_expediente"`);
    }

}
